routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SaleDetailsController;
use App\Http\Controllers\ProductsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::resource('saledetails', SaleDetailsController::class);
Route::resource('/', ProductsController::class);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $table = 'categories';

    protected $fillable = [
        'name',
    ];
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Category;

class Product extends Model
{
    use HasFactory;
    protected $table = 'products';

    protected $fillable = [
        'name',
        'category_id',
        'unit_price',
        'stock_balance',
    ];
    public function category() 
    {
        return $this->belongsTo(Category::class, 'category_id');
    }
}

app/Models/SaleDetail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SaleDetail extends Model
{
    use HasFactory;
    protected $table = 'sale_details';

    protected $fillable = [
        'sale_id',
        'product_id',
        'qty',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;

class ProductsController extends Controller
{
    public function index(){
        $products = Product::with('category')->get();
        return view('products.index',compact('products'));
    }
}

app/Http/Controllers/SaleDetailsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\SaleDetail;

class SaleDetailsController extends Controller
{
    public function index(){

    }
    public function create(){
        $products = Product::all();
        return view('sale_details.create',compact('products'));
    }

    public function store(Request $request){
        $user = SaleDetail::create([
            'sale_id' => $request->sale_id,
            'product_id' => $request->product_id,
            'qty' => $request->qty,
        ]);
        return redirect()->back()->with('success','Create Successfully!');
    }
}

resources/views/sale_details/create.blade.php
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <style>
            .fields{
                padding: 30px;
            }
        </style>
    </head>
    <body>
        @if (session()->has('success'))
        <div class="flex justify-content-end px-2 py-2">
        <div class="alert alert-info" align="center">
            <p class="text-lg">{{ session('success') }}</p>
            </div>
        </div>
        @endif
        <form action="{{route('saledetails.store')}}" class="d-flex justify-content-center fields" method="post">
            @csrf
            @method('POST')
            <div class="card col-lg-6">
                <div class="fields">
                    <h3 class="d-flex justify-content-center">Sale</h3>
                    <div class="mb-3">
                        <label class="form-label">Product</label>
                        <select class="form-select" aria-label="Default select example" name="product_id">
                            <option value="" selected>select product</option>
                            @foreach ($products as $product)
                            <option value="{{$product->id}}">{{$product->name}}</option>
                            @endforeach
                          </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">sale</label>
                        <input type="text" class="form-control" name="sale_id">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Quantity</label>
                        <input type="text" class="form-control" name="qty">
                    </div>
                    <button type="submit" class="btn btn-primary">save</button>
                    <a type="button" href="{{ url()->previous() }}" class="btn btn-secondary">Back</a>
                </div>
            </div>
          </form>
    </body>
</html>